CREATE TABLE ACCOUNT(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
USERNAME VARCHAR(10) 
NOT NULL PASSWORD VARCHAR(8) NOT NULL,
NICKNAME VARCHAR(20) NOT NULL,
DESCR VARCHAR(500),
PHOTO VARCHAR(256)
PRIMARY KEY (ID),UNIQUE (USERNAME, NICKNAME));


CREATE TABLE POST(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
AUTHOR_ID INTEGER NOT NULL, 
POST_TEXT VARCHAR(500), 
POST_TIME BIGINT NOT NULL, 
REPUBS INTEGER,PRIMARY KEY (ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES ACCOUNT (ID));


CREATE TABLE TOPIC(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TOPIC_TEXT VARCHAR(140) NOT NULL, 
POST_ID INTEGER NOT NULL, 
PRIMARY KEY (ID), 
FOREIGN KEY (POST_ID) REFERENCES POST (ID));


CREATE TABLE FOLLOW(FOLLOWING_ID INTEGER NOT NULL,
FOLLOWED_ID INTEGER NOT NULL, 
PRIMARY KEY (FOLLOWING_ID, FOLLOWED_ID), 
FOREIGN KEY (FOLLOWING_ID) REFERENCES ACCOUNT (ID), 
FOREIGN KEY (FOLLOWED_ID) REFERENCES ACCOUNT (ID));



UPDATE POST SET REPUBS = REPUBS + 1 WHERE ID = ?;


INSERT INTO ACCOUNT VALUES(DEFAULT, ?, ?, ?, ?, ?);
INSERT INTO POST VALUES(DEFAULT, ?, ?, ?, 0);
INSERT INTO TOPIC VALUES(DEFAULT, ?, ?);
INSERT INTO FOLLOW VALUES(?, ?);	


SELECT * FROM ACCOUNT;
SELECT PASSWORD FROM ACCOUNT WHERE USERNAME = ?;
SELECT * FROM ACCOUNT WHERE USERNAME = ?;
SELECT * FROM ACCOUNT WHERE NICKNAME = ?;
SELECT * FROM POST WHERE ID = ?;



SELECT p.ID, p.AUTHOR_ID, a.NICKNAME, p.POST_TEXT, p.POST_TIME, p.REPUBS  + 
FROM POST p, ACCOUNT a 
WHERE (p.AUTHOR_ID = a.ID) AND ((p.AUTHOR_ID = ?) OR (p.AUTHOR_ID IN (SELECT FOLLOWED_ID 
FROM FOLLOW 
WHERE FOLLOWING_ID = ?))) 
ORDER BY p.POST_TIME DESC;



SELECT p.ID, p.AUTHOR_ID, a.NICKNAME, p.POST_TEXT, p.POST_TIME, p.REPUBS 
FROM POST p, ACCOUNT a 
WHERE (p.AUTHOR_ID <> ?) AND (p.AUTHOR_ID = a.ID) 
ORDER BY p.POST_TIME DESC;



SELECT p.ID, p.AUTHOR_ID, a.NICKNAME, p.POST_TEXT, p.POST_TIME, p.REPUBS 
FROM POST p, ACCOUNT a 
WHERE (p.AUTHOR_ID = a.ID) AND (p.AUTHOR_ID IN (SELECT FOLLOWED_ID 
FROM FOLLOW 
WHERE FOLLOWING_ID = ?)) 
ORDER BY p.POST_TIME DESC;



SELECT f.FOLLOWED_ID, COUNT(f.FOLLOWING_ID) 
FROM FOLLOW f 
GROUP BY f.FOLLOWED_ID;



SELECT f.FOLLOWED_ID, COUNT(f.FOLLOWING_ID) 
FROM FOLLOW f 
WHERE (f.FOLLOWED_ID IN (SELECT FOLLOWED_ID FROM FOLLOW WHERE FOLLOWING_ID = ?)) 			
GROUP BY f.FOLLOWED_ID;



SELECT f.FOLLOWED_ID, COUNT(f.FOLLOWING_ID)
FROM FOLLOW f 
WHERE (f.FOLLOWED_ID IN (SELECT FOLLOWING_ID FROM FOLLOW WHERE FOLLOWED_ID = ?)) 		
GROUP BY f.FOLLOWED_ID;




SELECT p.ID, p.AUTHOR_ID, a.NICKNAME, p.POST_TEXT, p.POST_TIME, p.REPUBS 
FROM POST p, ACCOUNT a 
WHERE (p.AUTHOR_ID = ?) AND (p.AUTHOR_ID = a.ID) 
ORDER BY p.POST_TIME DESC;


SELECT f1.FOLLOWED_ID, f2.POP
FROM FOLLOW f1, (SELECT FOLLOWED_ID, COUNT(FOLLOWING_ID) as POP FROM FOLLOW GROUP BY FOLLOWED_ID) f2
WHERE (f1.FOLLOWING_ID = ?) AND (f2.FOLLOWED_ID = f1.FOLLOWING_ID);




SELECT  a.ID, a.USERNAME , a.PASSWORD , a.NICKNAME , a.DESCR , a.PHOTO 
FROM  ACCOUNT a, (SELECT FOLLOWED_ID, COUNT(FOLLOWING_ID) as POP 
FROM FOLLOW 
WHERE FOLLOWED_ID IN (SELECT FOLLOWED_ID FROM FOLLOW WHERE FOLLOWING_ID = ?) 
GROUP BY FOLLOWED_ID 
ORDER BY POP DESC) f 
WHERE (f.FOLLOWED_ID = a.ID);



SELECT a.ID, a.USERNAME, a.PASSWORD, a.NICKNAME, a.DESCR, a.PHOTO
FROM FOLLOW f, ACCOUNT a 
WHERE (f.FOLLOWED_ID = ?) AND (f.FOLLOWING_ID = a.ID);



SELECT p.ID, p.AUTHOR_ID, a.NICKNAME, p.POST_TEXT, p.POST_TIME, p.REPUBS 
FROM TOPIC t, POST p, ACCOUNT a 
WHERE (t.TOPIC_TEXT = ?) AND (t.POST_ID = p.ID) AND (p.AUTHOR_ID = a.ID) 
ORDER BY p.POST_TIME DESC;	



SELECT DISTINCT COUNT(FOLLOWING_ID) 
FROM FOLLOW 
WHERE (FOLLOWED_ID = ?) 
GROUP BY FOLLOWED_ID;



SELECT COUNT(FOLLOWED_ID) 
FROM FOLLOW 
WHERE (FOLLOWING_ID = ?)
GROUP BY FOLLOWING_ID;



